### ISSUE TITLE
Client QA request

### ISSUE THREAD

**Issue by steveoni** [datopian/ckanext-opendatani#34]
## Acceptance
- [ ] All task are done and resolved

## Task

- [ ] harvested data should be under NSIRA organization
- [ ] update the title of the dataset on the frontend search page to be just the title and no additional metadata
- [ ] update the `description` on the frontend search page to be the `title + metadata`
- [ ] Make the last updated for harvested metadata be in the actual data and not timeago format
- [ ] Add a link to the harvested data source
- [ ] Represent json format title with respective json format version e.g `json0.2`
- [ ] Update Application/Base64 to be Excel file xlsx
- [ ] Fix the download count issue
