### ISSUE TITLE
Migrate Prod to the latest ckan version

### ISSUE THREAD

**Issue by steveoni** [datopian/ckanext-opendatani#39]
The ckan version used in prod is now obsolete and needs to be updated for easy management by the SRE teams and easy bug fixes when needed

## Acceptance

- [x] Prod is updated to ckan 2.10.3 similar to what on Dev instance

## Task

- [x] The Dev backend still has some unfinished work. 
  - [x] the API Keys generation page is missing/absent (~ <2h)
  - [x] UI needs a bit of update in terms of responsiveness (~ < 5h)
- [x] Dev backend instance should be QAed to prevent unforeseen issues (ie. identifying currently unknown fixes that need to be made)
    - [x] organization page not showing package count for each organization
- [x] Copy config and update from Dev instance to Prod respectively ( < 2h )
- [ ] No DB migration was done for dev (might need to checkout with the SRE team to confirm if this is really needed). **NOTE:** we should backup all data in Production before doing the migration

**Comment by steveoni** [comment]
**Update from SRE**

To do migration, we need to run `db upgrade` command, and before then, there will be a backup set for the db.

**Comment by osahon-okungbowa** [comment]
migration has been completed successfully.

Closing this issue
